import { BUILD_PARTS, getBuildPart } from '../game/build-catalog.js';
import { loadGame } from '../game/state.js';
import { formatApiLogText, downloadTextFile } from './api-log.js';
import { PROVIDER_PRESETS, configSummary, loadApiConfig } from '../lib/providers.js';

export class ReportDownload {
  constructor() {
    document.getElementById('download-report')?.addEventListener('click', () => {
      downloadTextFile('tokemons-expert-feedback-report.txt', buildExpertReport());
    });
  }
}

function buildExpertReport(): string {
  const save = loadGame();
  const cfg = loadApiConfig();
  const villageCounts = new Map<number, number>();
  if (save) {
    for (const part of save.placedBlocks) {
      villageCounts.set(part.blockId, (villageCounts.get(part.blockId) ?? 0) + 1);
    }
  }
  const savedSummary = save
    ? [
        `Current save: yes`,
        `World seed: ${save.worldSeed}`,
        `Player position: (${save.playerX},${save.playerY})`,
        `Tokemon: ${save.tokemon.name}`,
        `Tokemon description: ${save.tokemon.description}`,
        `Tokemon gene seed: ${save.tokemon.genes.seed}`,
        `Tokemon body plan: ${save.tokemon.genes.bodyPlan}`,
        `Tokemon surface: ${save.tokemon.genes.surface}`,
        `Tokemon pattern: ${save.tokemon.genes.pattern}`,
        `Tokemon evolution stage: ${save.tokemon.genes.evolutionStage}`,
        `Placed village parts: ${save.placedBlocks.length}`,
        ...[...villageCounts.entries()].map(([id, count]) => {
          const part = getBuildPart(id);
          return `  - ${part.name}: ${count}`;
        }),
        `Biomes seen: ${save.memory.biomesSeen.join(', ') || 'none'}`,
        `Steps: ${save.memory.wanderSteps}`,
        `Chat turns: ${save.memory.chatTurns}`,
        `$LLM balance: ${save.memory.llmBalance}`,
        `Inspiration: ${save.memory.inspiration}`,
        `Entropy: ${save.memory.entropy}`,
        `Creativity: ${save.memory.creativity}`,
        `Energy: ${save.memory.energy}`,
        `Visited coordinates: ${save.memory.visitedCoords.length}`,
        `Looted coordinates: ${save.memory.lootedCoords?.length ?? 0}`,
        `Recent self-story: ${save.memory.selfStory.slice(-4).join(' | ') || 'none'}`,
        `Recent beliefs: ${save.memory.selfBeliefs.slice(-4).join(' | ') || 'none'}`,
      ].join('\n')
    : 'Current save: none';

  return [
    'TOKEMONS - EXPERT FEEDBACK REPORT',
    `Generated: ${new Date().toISOString()}`,
    'Purpose: A self-contained brief for external experts reviewing the game idea, mechanics, visuals, technical design, AI/memory systems, and current implementation risks.',
    '',
    '1. Executive Summary',
    'Tokemons is a browser-based procedural exploration game inspired by Game Boy visual constraints. The player creates a deterministic creature companion, explores an infinite seed-driven tile world, builds a village, and talks with the companion through configurable AI providers. The core fantasy is that the companion forms memory and identity through movement, places, dialogue, and construction.',
    'The game currently sits between prototype and vertical-slice: the main loop exists, procedural terrain exists, build mode exists, save/continue exists, AI chat exists, and the companion has persistent memory stats. The biggest design questions are whether exploration/build/chat combine into a compelling loop, whether the visuals read clearly at small tile scale, and whether the AI memory feels meaningful rather than decorative.',
    '',
    '2. Target Experience',
    '- Tone: intimate, mysterious, low-fi, exploratory, companion-driven.',
    '- Visual reference: limited-palette Game Boy / DMG-inspired pixel look, but implemented with Phaser vector/graphics calls rather than image tilemaps.',
    '- Emotional hook: the Tokemon is not just a pet; it is a small procedural mind that remembers places, talks back, and changes through the run.',
    '- Gameplay hook: the world is infinite and deterministic; each step can reveal new biomes, props, resources, memories, and build opportunities.',
    '- Player fantasy: wander with a strange companion, discover its identity, harvest relics, and slowly construct a personal village in an endless world.',
    '',
    '3. Current Player Flow and Controls',
    '- Boot scene: title screen with procedural preview; automatically proceeds if needed.',
    '- Create scene: generates a Tokemon preview. R rerolls, Enter starts a new run, C continues a saved run, L clears memory/save.',
    '- Play scene: player moves across the world while the companion follows.',
    '- Movement: WASD or arrow keys. Movement is logically grid-based but visually interpolated.',
    '- T: opens Tokemon chat.',
    '- P: opens AI provider settings.',
    '- G: toggles API call log.',
    '- Report button: downloads this expert-feedback report.',
    '- F: toggles autonomous wandering.',
    '- B: toggles build mode.',
    '- Build mode: 1-9 select build piece, Q/R cycle pieces, E or nearby click places, Delete/Backspace clears the tile ahead, B exits build mode.',
    '- Reset button: clears save and returns to creation.',
    '',
    '4. Core Gameplay Loop',
    'Primary loop:',
    '1. Create or continue a Tokemon.',
    '2. Explore deterministic terrain.',
    '3. Discover biomes and props.',
    '4. Gain or spend $LLM resources.',
    '5. Build village pieces.',
    '6. Talk with the Tokemon.',
    '7. Memory updates alter future context for dialogue and self-story.',
    '',
    'Secondary loop:',
    '- Mine/inspect special props such as crystals, ruins, shells, mushrooms, flowers, blossoms, berry bushes, cactus, rune stones, and obelisks.',
    '- Earn $LLM, inspiration, and energy.',
    '- Use $LLM for chat and construction.',
    '- Autonomous mode lets the creature/player continue wandering according to deterministic scoring.',
    '',
    '5. Build and Village System',
    'Build mode stores placed village pieces as numeric ids in save data for compatibility. Current pieces:',
    ...BUILD_PARTS.map((part) => `- ${part.id}: ${part.name} (${part.walkable ? 'walkable' : 'solid'}, cost ${part.cost} $LLM)`),
    'Roads, plazas, and farms are walkable. Buildings, fences, wells, towers, and shrines are solid. Major structures are rendered larger than a tile so they read as village objects rather than terrain markings.',
    'Design intent: allow players to build a small readable settlement using one-tile stamps. Current risk: single-tile footprints may limit village legibility; experts should evaluate whether multi-tile blueprints or adjacency bonuses are needed.',
    '',
    '6. Procedural World System',
    'The kernel samples cells from worldSeed and cell coordinates. Spatial generation must remain deterministic and must not use unseeded Math.random for world sampling. Fields include elevation, moisture, temperature, vegetation, weirdness, settlement, road, biomeId, terrainStyle, groundTileId, propId, and walkable.',
    'Sampler techniques:',
    '- `fbm2D` noise creates elevation, moisture, weirdness, settlement, vegetation, and temperature gradients.',
    '- `classifyBiome()` maps climate to biome families.',
    '- `cellSeed()` and `seedToFloat()` provide deterministic per-cell prop and visual rolls.',
    '- Chunk/local coordinates are used for stable sampling across infinite coordinates, including negative coordinates.',
    '- Roads derive from settlement noise and coordinate phases.',
    'Biome families:',
    '- Ocean and coast.',
    '- Meadow, deep forest, wetland.',
    '- Mountain and snowfield.',
    '- Desert.',
    '- Crystal fields.',
    '- Ancient ruins.',
    '- Urban fringe and town core.',
    'Prop families:',
    '- Obstacles: tree, rock, cactus, crystal, ruin, pine, rune stone, obelisk.',
    '- Vegetation: grass, tall grass, fern, bush, berry bush, vine, reeds, lily, scrub, blossom, flower, flower patch.',
    '- Flavor/town: shell, mushroom, lamp, sign, snowdrift, fountain.',
    '',
    '7. Visual Design and Readability',
    '- Palette: four-color Game Boy-inspired green palette: lightest, light, dark, darkest.',
    '- Rendering style: chunky pixel marks and geometric primitives through Phaser Graphics.',
    '- Terrain: biome-colored base tiles, dithered biome borders, micro details, elevation/cliff shadows, prop overlays, and dream/wisp overlays.',
    '- Entities: trainer sprite is baked from 16x16 pixel data and enlarged; Tokemon sprite is generated from genes and baked to canvas.',
    '- Buildings: rendered as larger pixel-art graphics with roof silhouettes, doors, windows, farm rows, shrine glow, well glint, and tower height.',
    '- UI: retro panels, heavy borders, monospace pixel font, HUD stats, chat panel, API provider panel, API log panel.',
    'Current visual risks:',
    '- Tiny tile scale can make terrain, props, and buildings compete for attention.',
    '- Buildings are single-tile logical objects but visually extend beyond tile bounds.',
    '- HUD and panels can obscure the world on small screens.',
    '- The all-green palette is thematically strong but may reduce readability or accessibility.',
    '',
    '8. Rendering and Performance',
    'The client uses Phaser graphics drawing. The world renderer draws only the visible viewport plus margin, caches sampled cells per viewport draw, and reuses neighbor samples for biome transitions and cliff/shadow edges. Movement is still grid-based for gameplay determinism, but visual player/camera interpolation is fractional and eased for smoother motion.',
    'Performance budget:',
    '- Viewport-only rendering, no full-world tilemap.',
    '- Approximately width/16 by height/16 visible cells plus margin.',
    '- Per-cell budget: one base fill, one ground detail, one prop or vegetation object, one placed block override.',
    '- Phaser Graphics is flexible but can become expensive if every cell gets many primitives.',
    '- Current optimization: per-frame cell cache inside `drawWorld()` to avoid repeated neighbor sampling.',
    'Movement feel:',
    '- Grid position updates immediately for gameplay/save logic.',
    '- Visual player position tweens to the next cell.',
    '- Camera interpolates toward the visual player.',
    '- Phaser `roundPixels` is disabled to avoid sub-tile snapping.',
    '',
    '9. AI Provider System',
    `Configured provider summary: ${configSummary(cfg)}`,
    'Supported presets:',
    ...PROVIDER_PRESETS.map((preset) => `- ${preset.label}: ${preset.baseUrl}, default model ${preset.defaultModel || '(custom)'}, ${preset.needsKey ? 'requires key' : 'key optional/local'}`),
    'Routing behavior:',
    '- Local providers such as Ollama and LM Studio can be called directly from browser when available.',
    '- Hosted providers should route through /api/chat proxy for production safety.',
    '- API keys are stored in browser localStorage for local play/configuration.',
    '- API calls are logged in the on-screen API log and included in this report.',
    '- Offline/mock behavior provides a fallback when provider config is missing.',
    '',
    '10. Memory, Companion Identity, and Economy',
    'The companion tracks:',
    '- selfStory: rolling narrative lines about identity and experience.',
    '- selfBeliefs: distilled beliefs from dialogue and events.',
    '- episodes: bounded event memory including genesis, awakening, biome discovery, chat, reflection, build, and discovery.',
    '- biomesSeen.',
    '- wanderSteps and chatTurns.',
    '- visitedCoords and lootedCoords.',
    '- $LLM balance.',
    '- inspiration, entropy, creativity, and energy.',
    'Memory affects prompts through `formatMemoryForPrompt()`, which retrieves recent and coordinate/biome-relevant episodes. The design goal is for the creature to speak with continuity, remember places, and turn play into identity.',
    'Economy:',
    '- Manual chat costs $LLM.',
    '- Construction costs $LLM based on piece type.',
    '- Biome discoveries, level-ups, and mining can mint $LLM.',
    '- Terrain can restore or drain energy.',
    '- Props can influence creativity/inspiration.',
    'Current design risk: $LLM may feel like a wrapper over chat/build gating unless experts can identify meaningful choices around earning and spending.',
    '',
    '11. Autonomous Mode',
    'Autonomous mode lets the game choose movement directions while energy remains. It scores walkable neighboring cells using unvisited coordinate boost, unseen biome boost, and deterministic seeded variation. Every twentieth autonomous step can trigger an AI reflection if chat is not busy.',
    'Design intent: make the Tokemon feel like it has agency and curiosity. Current design risk: autonomy may feel more like auto-walk than personality unless feedback, animation, and decision transparency improve.',
    '',
    '12. Technology Stack and Project Structure',
    'Technology stack:',
    '- TypeScript.',
    '- Vite.',
    '- Phaser 3.',
    '- npm workspaces.',
    '- Vitest for kernel tests.',
    '- Browser localStorage for save/config.',
    '- Serverless API route at /api/chat for hosted AI provider proxy.',
    'Project map:',
    '- packages/client: Phaser game, scenes, UI panels, rendering, save flow.',
    '- packages/kernel: deterministic world sampler, biomes, noise, cell contracts.',
    '- packages/tokemon-gen: Tokemon genes, names, sprite baking.',
    '- api: serverless chat endpoint.',
    '- docs: architecture, deployment, budget, and roadmap notes.',
    'Important implementation files:',
    '- packages/client/src/scenes/BootScene.ts: title/preview scene.',
    '- packages/client/src/scenes/CreateScene.ts: Tokemon creation/continue flow.',
    '- packages/client/src/scenes/PlayScene.ts: gameplay, movement, build, HUD, interaction.',
    '- packages/client/src/game/world-draw.ts: viewport world drawing and walkability.',
    '- packages/client/src/game/render/*.ts: terrain, props, dream overlays, buildings.',
    '- packages/client/src/game/state.ts: save/runtime state.',
    '- packages/client/src/game/memory.ts: companion memory/economy.',
    '- packages/client/src/ui/chat.ts: chat panel.',
    '- packages/client/src/ui/settings.ts: AI provider settings.',
    '- packages/client/src/ui/api-log.ts: API call log and download.',
    '- packages/client/src/ui/report.ts: this report generator.',
    '- packages/kernel/src/sample-cell.ts: procedural cell sampling.',
    '- packages/kernel/src/biome.ts: biome classification.',
    '- packages/kernel/src/seed.ts: deterministic seed utilities.',
    '',
    '13. Save Data and Compatibility',
    '- Save key: tokemons_save_v2.',
    '- Save contains version, worldSeed, player position, Tokemon, placedBlocks, mood, and memory.',
    '- Placed village pieces are stored as numeric ids with coordinates.',
    '- Runtime converts placedBlocks to a Map for fast lookup.',
    '- Legacy v1 saves are migrated into v2 memory defaults.',
    '- Save format changes should bump version and include migration.',
    '',
    '14. Current Runtime Snapshot',
    savedSummary,
    '',
    '15. Known Strengths',
    '- Coherent identity: procedural world, creature memory, and village building all support the same theme of becoming through place.',
    '- Deterministic kernel: world can be reproduced from seed and coordinates.',
    '- Local/hosted AI flexibility: supports multiple provider styles.',
    '- Small code surface: core systems are inspectable and easy to iterate.',
    '- Low-fi renderer: assets are generated/drawn procedurally, keeping content lightweight.',
    '',
    '16. Known Weaknesses and Risks',
    '- The world may still feel like a visual sampler until more goals, encounters, and consequences exist.',
    '- Building is currently single-tile stamping; larger village planning may need multi-tile footprints, adjacency rules, or resource chains.',
    '- AI chat depends heavily on provider setup and model quality.',
    '- Memory may feel abstract unless surfaced through behavior, quests, or visible companion changes.',
    '- Visual readability at 16px tile scale needs expert review, especially for buildings and props.',
    '- Phaser Graphics per-cell rendering could become a bottleneck as detail increases.',
    '- The UI uses dense retro text that may be hard on small screens.',
    '',
    '17. Expert Feedback Questions - Game Mechanics',
    '- Is the core loop clear: explore, remember, chat, build, repeat?',
    '- Does $LLM create interesting choices or just friction?',
    '- Are mining, discovery, building, and chatting balanced against each other?',
    '- Should the village system reward adjacency, roads, districts, or biome-specific building bonuses?',
    '- Should autonomous mode be framed as creature agency, auto-explore, or a separate simulation state?',
    '- What short-term goals should exist beyond wandering and building?',
    '- What would make the companion feel more alive outside chat text?',
    '',
    '18. Expert Feedback Questions - Visuals and UX',
    '- Are terrain, props, buildings, player, and companion visually separable at normal browser zoom?',
    '- Do larger buildings feel readable or do they conflict with single-tile collision?',
    '- Is the all-green Game Boy palette charming or too limiting?',
    '- Is the HUD too dense or placed poorly?',
    '- Are controls discoverable enough?',
    '- Is movement smooth enough while preserving grid clarity?',
    '- Are UI panels readable and nonintrusive?',
    '- What accessibility improvements are needed for contrast, text size, motion, and keyboard use?',
    '',
    '19. Expert Feedback Questions - AI and Narrative',
    '- Does the memory model support believable continuity?',
    '- Which memory events should matter most to dialogue?',
    '- Should companion personality affect movement/build suggestions?',
    '- Should the Tokemon initiate goals or requests?',
    '- Should AI output influence mechanics, or remain expressive flavor?',
    '- How should the game handle offline play without AI?',
    '',
    '20. Expert Feedback Questions - Technical Implementation',
    '- Is deterministic world sampling robust enough for infinite exploration?',
    '- Should placed village pieces move into kernel contracts instead of client runtime state?',
    '- Is Phaser Graphics the right renderer long-term, or should terrain/buildings move toward tilemaps/sprites?',
    '- Is the API proxy/key safety model suitable for deployment?',
    '- Are save migrations and versioning sufficient?',
    '- What tests should be added beyond seed determinism?',
    '- What profiling should be done before adding more visual detail?',
    '',
    '21. Suggested Evaluation Checklist',
    '- Start a new run and reroll Tokemons several times.',
    '- Walk through at least three biome types.',
    '- Mine/inspect several props.',
    '- Open chat with T and test with configured and unconfigured providers.',
    '- Build a small village using every build part.',
    '- Toggle autonomous mode and observe decision quality.',
    '- Download API log and report.',
    '- Resize browser/mobile viewport and check UI fit.',
    '- Continue from save and verify state continuity.',
    '',
    '22. Current Design Decisions Needing Confirmation',
    '- Keep grid-based movement but smooth visual interpolation.',
    '- Keep single-tile logical buildings with oversized visuals.',
    '- Keep four-color Game Boy palette.',
    '- Keep $LLM as shared resource for chat/building.',
    '- Keep provider configuration inside browser for local play.',
    '- Keep world generation deterministic and separated in kernel package.',
    '',
    '23. Previous Feedback-Driven Fixes Already Applied',
    '- Removed duplicate API provider form and made it closeable.',
    '- Changed in-game chat from C to T so C remains continue on create screen.',
    '- Added village build catalog with nine build pieces.',
    '- Enlarged and clarified building sprites.',
    '- Smoothed movement and optimized viewport cell sampling.',
    '- Added API call log and downloadable expert report.',
    '',
    '24. Recent API Call Log',
    formatApiLogText(),
  ].join('\n');
}
